### ISSUE TITLE
exe错误提示

### ISSUE THREAD

**Issue by H4ckBu7eer-EX** [CrystalEggs/Manual-Selection-Tool-Python-Version#1]
exe错误 无法运行

**Comment by H4ckBu7eer-EX** [comment]
问题出在调用汇率查询网站的API的地方 那个汇率网站已经无法访问了

`
Traceback (most recent call last):
  File "Manual_Selection_Tool.py", line 85, in <module>
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1377, in http_open
  File "urllib\request.py", line 1352, in do_open
  File "http\client.py", line 1374, in getresponse
  File "http\client.py", line 318, in begin
  File "http\client.py", line 287, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response
`

**Comment by H4ckBu7eer-EX** [comment]
版主什么时候更新

**Comment by LanceHuang245** [comment]
马上进行修复。
